//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshersPool1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_JobPreferences
    {
        public int CandidateID { get; set; }
        public string SignBond { get; set; }
        public string NightShifts { get; set; }
        public string Relocate { get; set; }
        public string RelocationCity1 { get; set; }
        public string RelocationCity2 { get; set; }
        public string RelocationCity3 { get; set; }
        public string RelocationCity4 { get; set; }
    }
}
