//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshersPool1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_MentorRatings
    {
        public int CandidateID { get; set; }
        public int TestID { get; set; }
        public string Personality { get; set; }
        public string Communication { get; set; }
        public string ConfidenceLevels { get; set; }
        public string English { get; set; }
        public string GeneralAptitude { get; set; }
        public string AnalyticalAbilities { get; set; }
        public string MentorRemarks1 { get; set; }
        public string MentorRemarks2 { get; set; }
        public string MentorRemarks3 { get; set; }
    
        public virtual CA_PersonalData CA_PersonalData { get; set; }
    }
}
