//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshersPool1.Models
{
    using System;
    using System.Collections.Generic;
    
    
    
using System.ComponentModel.DataAnnotations;public partial class CA_PersonalData
    {
        public CA_PersonalData()
        {
            this.CA_Languages = new HashSet<CA_Languages>();
            this.CA_MentorRatings = new HashSet<CA_MentorRatings>();
            this.CA_Skills = new HashSet<CA_Skills>();
            this.EM_JobPostings_Shortlistings = new HashSet<EM_JobPostings_Shortlistings>();
        }
    
        public int CandidateID { get; set; }
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        [Required(ErrorMessage = "Please Enter your FirstName")]
        [MaxLength(30, ErrorMessage = "Cannot be longer than 10 characters")]
        [StringLength(30, ErrorMessage = "Cannot be longer than 10 characters")]
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string FatherName { get; set; }
        public string Category { get; set; }
        public int YearsofExperience { get; set; }
        public string CurrentLocation { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string PrimaryEmail { get; set; }
        public string SecondaryEmail { get; set; }
        public string MobileNo { get; set; }
        public string LandlineNo { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public string MotherTongue { get; set; }
        public string UniversityID { get; set; }
    
        public virtual CA_Academics CA_Academics { get; set; }
        public virtual ICollection<CA_Languages> CA_Languages { get; set; }
        public virtual ICollection<CA_MentorRatings> CA_MentorRatings { get; set; }
        public virtual MS_LanguageMaster MS_LanguageMaster { get; set; }
        public virtual ICollection<CA_Skills> CA_Skills { get; set; }
        public virtual ICollection<EM_JobPostings_Shortlistings> EM_JobPostings_Shortlistings { get; set; }
    }
}
