//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshersPool1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_ProfessionalCourses
    {
        public string PCNo { get; set; }
        public int CandidateID { get; set; }
        public string Particulars { get; set; }
        public string Institution { get; set; }
        public string Place { get; set; }
        public string FromDT { get; set; }
        public string ToDT { get; set; }

        public CA_PersonalData CA_PersonalData { get; set; }
    }
}
