//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshersPool1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_RolePreferences
    {
        public string CandidateID { get; set; }
        public string RoleID { get; set; }
        public string Priority { get; set; }
    
        public virtual MS_RoleMaster MS_RoleMaster { get; set; }
    }
}
