//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshersPool1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_Skills
    {
        public int CandidateID { get; set; }
        public string SkillID { get; set; }
        public string SkillLevelID { get; set; }
    
        public virtual CA_PersonalData CA_PersonalData { get; set; }
        public virtual MS_SkillLevelMaster MS_SkillLevelMaster { get; set; }
        public virtual MS_SkillMaster MS_SkillMaster { get; set; }
    }
}
