//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshersPool1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EM_EmployerData
    {
        public EM_EmployerData()
        {
            this.EM_JobPostings = new HashSet<EM_JobPostings>();
        }
    
        public int EmployerID { get; set; }
        public string Name { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string HeadQuarters { get; set; }
        public string Founder { get; set; }
        public string Description { get; set; }
        public string Domain { get; set; }
        public string Logo { get; set; }
        public string Website { get; set; }
        public string CompanyEmail { get; set; }
        public string ContactNumber { get; set; }
    
        public virtual ICollection<EM_JobPostings> EM_JobPostings { get; set; }
    }
}
