//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshersPool1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EM_JobPostings_Shortlistings
    {
        public int JobID { get; set; }
        public int CandidateID { get; set; }
        public string Result { get; set; }
    
        public virtual CA_PersonalData CA_PersonalData { get; set; }
        public virtual MS_ResultMaster MS_ResultMaster { get; set; }

        public EM_JobPostings EM_JobPostings { get; set; }
    }
}
