//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshersPool1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EM_JobPostings
    {
        public int JobID { get; set; }
        public int EmployerID { get; set; }
        public string RoleID { get; set; }
        public string StreamID { get; set; }
        public string JobTitle { get; set; }
        public string JobDescription { get; set; }
        public string DriveType { get; set; }
        public string Location { get; set; }
        public string CityID { get; set; }
        public string CityName { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual EM_EmployerData EM_EmployerData { get; set; }
        public virtual MS_CityMaster MS_CityMaster { get; set; }
        public virtual MS_DriveMaster MS_DriveMaster { get; set; }
        public virtual MS_RoleMaster MS_RoleMaster { get; set; }
    }
}
