//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshersPool1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Team2_FRESHERSPOOLEntities : DbContext
    {
        public Team2_FRESHERSPOOLEntities()
            : base("name=Team2_FRESHERSPOOLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CA_Academics> CA_Academics { get; set; }
        public DbSet<CA_JobPreferences> CA_JobPreferences { get; set; }
        public DbSet<CA_Languages> CA_Languages { get; set; }
        public DbSet<CA_MentorRatings> CA_MentorRatings { get; set; }
        public DbSet<CA_PersonalData> CA_PersonalData { get; set; }
        public DbSet<CA_PlacementHistory> CA_PlacementHistory { get; set; }
        public DbSet<CA_ProfessionalCourses> CA_ProfessionalCourses { get; set; }
        public DbSet<CA_RolePreferences> CA_RolePreferences { get; set; }
        public DbSet<CA_Skills> CA_Skills { get; set; }
        public DbSet<CO_College> CO_College { get; set; }
        public DbSet<EM_EmployerData> EM_EmployerData { get; set; }
        public DbSet<EM_JobPostings> EM_JobPostings { get; set; }
        public DbSet<EM_JobPostings_Shortlistings> EM_JobPostings_Shortlistings { get; set; }
        public DbSet<EM_JobPostings_Skillset> EM_JobPostings_Skillset { get; set; }
        public DbSet<MS_CityMaster> MS_CityMaster { get; set; }
        public DbSet<MS_DriveMaster> MS_DriveMaster { get; set; }
        public DbSet<MS_LanguageMaster> MS_LanguageMaster { get; set; }
        public DbSet<MS_ResultMaster> MS_ResultMaster { get; set; }
        public DbSet<MS_RoleMaster> MS_RoleMaster { get; set; }
        public DbSet<MS_SkillLevelMaster> MS_SkillLevelMaster { get; set; }
        public DbSet<MS_SkillMaster> MS_SkillMaster { get; set; }
        public DbSet<MS_StreamMaster> MS_StreamMaster { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
