//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshersPool1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_LanguageMaster
    {
        public MS_LanguageMaster()
        {
            this.CA_Languages = new HashSet<CA_Languages>();
            this.CA_PersonalData = new HashSet<CA_PersonalData>();
        }
    
        public string LanguageID { get; set; }
        public string Language { get; set; }
    
        public virtual ICollection<CA_Languages> CA_Languages { get; set; }
        public virtual ICollection<CA_PersonalData> CA_PersonalData { get; set; }
    }
}
