//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshersPool1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_ResultMaster
    {
        public MS_ResultMaster()
        {
            this.CA_PlacementHistory = new HashSet<CA_PlacementHistory>();
            this.EM_JobPostings_Shortlistings = new HashSet<EM_JobPostings_Shortlistings>();
        }
    
        public string Result { get; set; }
    
        public virtual ICollection<CA_PlacementHistory> CA_PlacementHistory { get; set; }
        public virtual ICollection<EM_JobPostings_Shortlistings> EM_JobPostings_Shortlistings { get; set; }
    }
}
