//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshersPool1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_SkillMaster
    {
        public MS_SkillMaster()
        {
            this.CA_Skills = new HashSet<CA_Skills>();
        }
    
        public string SkillID { get; set; }
        public string SkillDesc { get; set; }
    
        public virtual ICollection<CA_Skills> CA_Skills { get; set; }
    }
}
